# Config file for Pelorus project
# https://github.com/konveyor/pelorus/

# Deploy only one exporter with multiple deployment methods.
#

openshift_prometheus_htpasswd_auth: internal:{SHA}+pvrmeQCmtWmYVOZ57uuITVghrM=
openshift_prometheus_basic_auth_pass: changeme
extra_prometheus_hosts:

# Uncomment this if your cluster serves privately signed certificates
# custom_ca: true

deployment:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: pelorus
    app.kubernetes.io/version: v0.33.0

exporters:
  instances:
  - app_name: deploytime-exporter
    exporter_type: deploytime
    extraEnv:
    - name: NAMESPACES
      value: mongo-persistent

  - app_name: committime-exporter
    exporter_type: committime
    extraEnv:
    - name: NAMESPACES
      value: mongo-persistent

  - app_name: latest-custom-imagetag-deploytime-exporter
    exporter_type: deploytime
    image_tag: latest
    extraEnv:
    - name: NAMESPACES
      value: mongo-persistent

  - app_name: latest-custom-imagetag-committime-exporter
    exporter_type: committime
    image_tag: latest
    extraEnv:
    - name: NAMESPACES
      value: mongo-persistent

  - app_name: git-custom-url-deploytime-exporter
    exporter_type: deploytime
    source_url: https://github.com/konveyor/pelorus.git
    extraEnv:
    - name: NAMESPACES
      value: mongo-persistent

  - app_name: git-custom-url-committime-exporter
    exporter_type: committime
    source_url: https://github.com/konveyor/pelorus.git
    extraEnv:
    - name: NAMESPACES
      value: mongo-persistent

  - app_name: git-custom-source-ref-deploytime-exporter
    exporter_type: deploytime
    source_ref: master
    extraEnv:
    - name: NAMESPACES
      value: mongo-persistent

  - app_name: git-custom-source-ref-committime-exporter
    exporter_type: committime
    source_ref: master
    extraEnv:
    - name: NAMESPACES
      value: mongo-persistent
